version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
       ci-dependencies:
          patterns:
            - "*" # Match all CI dependencies to one PR.
