addSbtPlugin("ch.epfl.scala"                % "sbt-scalafix"         % "0.12.0")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.21")
addSbtPlugin("com.github.sbt"               % "sbt-native-packager"  % "1.10.0")
addSbtPlugin("nl.gn0s1s"                    % "sbt-dotenv"           % "3.0.0")
addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.2")
addSbtPlugin("org.typelevel"                % "sbt-tpolecat"         % "0.5.1")
